move-html: create-routes
	cp ./dist/index.html ./dist/sign-up
	cp ./dist/index.html ./dist/log-in
	cp ./dist/index.html ./dist/main-page
	cp ./dist/index.html ./dist/profile
	cp ./dist/index.html ./dist/settings
	cp ./dist/index.html ./dist/chat
	cp ./dist/index.html ./dist/chats
	cp ./dist/index.html ./dist/structurized-messages

create-routes:
	mkdir ./dist/sign-up
	mkdir ./dist/log-in
	mkdir ./dist/main-page
	mkdir ./dist/profile
	mkdir ./dist/settings
	mkdir ./dist/chat
	mkdir ./dist/chats
	mkdir ./dist/structurized-messages