export const WEBSOCKET_URL = 'wss://skill-sharing.ru/api/v1/chat/ws?user_id=';
export const BACK_URL = 'https://skill-sharing.ru/api/v1';
export const STATIC_URL = BACK_URL + '/static';
export const AVATAR_URL = STATIC_URL + '/avatars/';
export const VOICE_URL = STATIC_URL + '/voice/';
export const ATTACHMENTS_URL = STATIC_URL + '/attachments/';
export const MATERIALS_URL = STATIC_URL + '/materials';
export const AUTH_URL = '/auth';
export const SIGN_UP_URL = AUTH_URL + '/sign-up';
export const LOG_IN_URL = AUTH_URL + '/log-in';
export const USERS_URL = '/users';
export const CHAT_URL = '/chat';
export const STUDY_MATERIALS_URL = '/study-materials';
export const REVIEW_URL = '/review';
